version: '3.8'
services:
  db:
    image: mysql:9.3.0
    #image: mysql:8.0
    container_name: culturalcalendar-db
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ROOT_HOST=% 
    #command: docker exec -it culturalcalendar-db mysql -uroot -proot
    #command: --mysql_native_password=on
    #command: --default-authentication-plugin=caching_sha2_password
    #command: --default-authentication-plugin=mysql_native_password
    #command: --mysql-native-password=ON --skip-host-cache --skip-name-resolve
    restart: unless-stopped
    volumes:
      - /tmp/CulturalCalendar/mysqld:/var/run/mysqld
      - ./db:/var/lib/mysql
    healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", MYSQL_DATABASE]
        interval: 5s
        timeout: 5s
        retries: 5  

  web:
    build: .
    container_name: culturalcalendar-web
    #command: python server/manage.py runserver 127.0.0.1:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/CulturalCalendar
    env_file:
      - .env
    environment:
      - SECRET_KEY=${DJANGO_SECRET_KEY}
    depends_on:
      db:
        condition: service_healthy
volumes:
  mysql_data: