# Generated by Django 4.2.20 on 2025-05-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_options_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Администратор'), (2, 'Пользователь')], default=2, verbose_name='Тип пользователя'),
        ),
    ]
