# Generated by Django 4.2.20 on 2025-05-02 17:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('website', models.URLField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3)])),
                ('date', models.DateTimeField()),
                ('duration', models.CharField(blank=True, max_length=20, null=True, verbose_name='Длительность')),
                ('stage', models.CharField(blank=True, max_length=100, null=True, verbose_name='Сцена')),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('genre', models.CharField(choices=[('concert', 'Концерт'), ('performance', 'Спектакль'), ('drama', 'Драма'), ('comedy', 'Комедия'), ('tragedy', 'Трагедия'), ('musical', 'Мюзикл'), ('ballet', 'Балет'), ('opera', 'Опера'), ('circusPerformance', 'Цирковое представление'), ('default', 'Не определено')], default='default', max_length=20)),
                ('min_age', models.PositiveIntegerField(default=12)),
                ('is_premiere', models.BooleanField(default=False)),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='affiche.theater')),
            ],
            options={
                'verbose_name': 'Постановка',
                'verbose_name_plural': 'Постановки',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_type', models.CharField(choices=[('main', 'Основная сцена'), ('small', 'Малый зал'), ('big', 'Большой зал'), ('other', 'Другая площадка')], default='main', max_length=10)),
                ('address', models.TextField(blank=True, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='affiche.performance')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='affiche.performance')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActorRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor_roles', to='affiche.performance')),
            ],
        ),
    ]
