# Generated by Django 4.2.20 on 2025-05-14 15:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('affiche', '0002_remove_location_performance_alter_performance_genre_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='theater',
            options={'verbose_name': 'Театр', 'verbose_name_plural': 'Театры'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='performance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='affiche.performance', verbose_name='Постановка'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='Текст комментария'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='date',
            field=models.DateTimeField(verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='genre',
            field=models.CharField(choices=[('performance', 'Спектакль'), ('tragicomedy', 'Трагикомедия'), ('drama', 'Драма'), ('comedy', 'Комедия'), ('baby', 'Для детей'), ('musical', 'Мюзикл'), ('show', 'Шоу')], default='default', max_length=20, verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на изображение'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='is_premiere',
            field=models.BooleanField(default=False, verbose_name='Премьера'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='min_age',
            field=models.PositiveIntegerField(default=12, verbose_name='Минимальный возраст'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='source_url',
            field=models.URLField(blank=True, null=True, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='affiche.theater', verbose_name='Театр'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='title',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Название постановки'),
        ),
        migrations.AlterField(
            model_name='theater',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='theater',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название театра'),
        ),
        migrations.AlterField(
            model_name='theater',
            name='website',
            field=models.URLField(verbose_name='Ссылка'),
        ),
    ]
