# Generated by Django 4.2.20 on 2025-05-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiche', '0004_alter_comment_created_at_alter_comment_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_edited',
            field=models.BooleanField(default=False, verbose_name='Редактировался'),
        ),
    ]
