# Generated by Django 4.2.20 on 2025-05-14 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiche', '0005_comment_is_edited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_edited',
        ),
    ]
